# Generated by Django 4.2.3 on 2023-07-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saturday_start", models.TimeField()),
                ("saturday_end", models.TimeField()),
                ("sunday_start", models.TimeField()),
                ("sunday_end", models.TimeField()),
                ("monday_start", models.TimeField()),
                ("monday_end", models.TimeField()),
                ("tuesday_start", models.TimeField()),
                ("tuesday_end", models.TimeField()),
                ("wednesday_start", models.TimeField()),
                ("wednesday_end", models.TimeField()),
                ("thursday_start", models.TimeField()),
                ("thursday_end", models.TimeField()),
                ("friday_start", models.TimeField()),
                ("friday_end", models.TimeField()),
                ("is_open_in_holidays", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Workhouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("appointment_price", models.IntegerField()),
                ("emerency_appointment_price", models.IntegerField()),
                ("appointment_time", models.IntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.city",
                    ),
                ),
                ("images", models.ManyToManyField(to="main.imagemodel")),
                ("service_types", models.ManyToManyField(to="mechanic.servicetype")),
                (
                    "work_time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mechanic.worktime",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
