# Generated by Django 4.2.3 on 2023-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktime",
            name="friday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="friday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="monday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="monday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="saturday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="saturday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="sunday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="sunday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="thursday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="thursday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="tuesday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="tuesday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="wednesday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worktime",
            name="wednesday_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
